server:
  applicationContextPath: /
  adminContextPath: /

  applicationConnectors:
  - type: http
    port: 9500
  adminConnectors:
  - type: http
    port: 9501

logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
  appenders:
  - type: console
    timeZone: UTC

database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: root
  url: jdbc:postgresql://localhost/postgres
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

